# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
  version "2.11.0"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/defai-digital/ax-code/releases/download/v2.11.0/ax-code-darwin-arm64.zip"
      sha256 "0dc1549b2661e373c9717baae3c6590da9429e7e8c7458d59d0d4ebc25305329"
      def install
        bin.install "ax-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/defai-digital/ax-code/releases/download/v2.11.0/ax-code-linux-x64.tar.gz"
      sha256 "21dcdc0f4948a9255127f9e92f1e472a3b3e9a39bd691860b1990b69b802d455"
      def install
        bin.install "ax-code"
      end
    end
  end
end
