# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
#
# Source-distribution variant of ax-code. Ships pre-bundled JavaScript
# plus the bun runtime as a Homebrew dependency. Avoids the
# bun build --compile × Worker bug class that affects the compiled
# binary on some terminals (oven-sh/bun#26762, #27766, #29124).
#
# This is the additive opt-in formula introduced by ADR-002 Phase 2.
# The default `ax-code` formula continues to ship the compiled binary
# until ADR-002 Phase 3 flips the default.
class AxCodeSource < Formula
  desc "Sovereign AI coding agent (source distribution)"
  homepage "https://github.com/defai-digital/ax-code"
  url "https://registry.npmjs.org/@defai.digital/ax-code-source/-/ax-code-source-4.0.18.tgz"
  sha256 "1f0d97c8a6ea5d54591e4e40c7b0e37ef40b09dc9e82ba56b44b4495628ecc83"
  version "4.0.18"
  license "MIT"

  depends_on "bun"
  depends_on "ripgrep"

  def install
    libexec.install Dir["*"]

    (bin/"ax-code").write <<~EOS
      #!/bin/sh
      AX_CODE_ORIGINAL_CWD="$(pwd)" exec "#{Formula["bun"].opt_bin}/bun" "#{libexec}/bundle/index.js" "$@"
    EOS
    (bin/"ax-code").chmod 0755
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
