# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
#
# Source-distribution variant of ax-code. Ships pre-bundled JavaScript
# plus the bun runtime as a Homebrew dependency.
#
# Compatibility formula for users who intentionally need the source+bun
# launcher. The default `ax-code` formula tracks compiled release assets.
class AxCodeSource < Formula
  desc "Sovereign AI coding agent (source distribution)"
  homepage "https://github.com/defai-digital/ax-code"
  url "https://registry.npmjs.org/@defai.digital/ax-code-source/-/ax-code-source-4.5.0.tgz"
  sha256 "f4d75d32ab70969a7ced465d61ecb3079390eb335977ae71646312d602628b52"
  version "4.5.0"
  license "MIT"

  depends_on "bun"
  depends_on "ripgrep"

  def install
    libexec.install Dir["*"]

    (bin/"ax-code").write <<~EOS
      #!/bin/sh
      AX_CODE_ORIGINAL_CWD="$(pwd)" exec "#{Formula["bun"].opt_bin}/bun" "#{libexec}/bundle/index.js" "$@"
    EOS
    (bin/"ax-code").chmod 0755
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
