# typed: false
# frozen_string_literal: true

# Auto-generated by ax-code release tooling — do not edit manually.
#
# Default compiled-binary formula for ax-code.
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
  version "5.9.1"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    url "https://github.com/defai-digital/ax-code/releases/download/v5.9.1/ax-code-darwin-arm64.zip"
    sha256 "5dc0aeca836ad7c22c17cd524b94b1241671225d21f9bc5091e0937dadc92908"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/defai-digital/ax-code/releases/download/v5.9.1/ax-code-linux-arm64.tar.gz"
      sha256 "2e17a003287632ee3cfc672974f9372069ec788967ad44737b0b36705eddc609"
    else
      url "https://github.com/defai-digital/ax-code/releases/download/v5.9.1/ax-code-linux-x64-baseline.tar.gz"
      sha256 "e6089ab22d40168bf0aaddc63d23bea84c883552916fe01f54c9e20c5fb56bb3"
    end
  end

  depends_on "ripgrep"

  def install
    bin.install "ax-code"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
