# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
  version "2.9.3"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/defai-digital/ax-code/releases/download/v2.9.3/ax-code-darwin-arm64.zip"
      sha256 "4d2215409960fefcfb97993c40b75b7d92d77746979c8142c515f7aa73d33930"
      def install
        bin.install "ax-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/defai-digital/ax-code/releases/download/v2.9.3/ax-code-linux-x64.tar.gz"
      sha256 "9d574f0af7886a869dd699207e07e2cd02ba751a79d5d48634153882029a3b07"
      def install
        bin.install "ax-code"
      end
    end
  end
end
